import { useEffect, useMemo, useState } from 'react';
import { MessageSquare, Star, SmilePlus } from 'lucide-react';
import { useAuth } from '@/lib/auth-context';
import { getFeedback } from '@/lib/services';
import type { Feedback } from '@/types';
import { PageHeader } from '@/components/admin/PageBits';
import { StatCard } from '@/components/ui';
import { demoFeedback } from '@/data/demo';
import { formatDate } from '@/lib/utils';

export default function FeedbackPage(){const{restaurant}=useAuth();const[rows,setRows]=useState<Feedback[]>([]);useEffect(()=>{if(!restaurant)return;(async()=>{try{const r=await getFeedback(restaurant.id);setRows(r.length?r:demoFeedback.map(x=>({...x,restaurant_id:restaurant.id})));}catch{setRows(demoFeedback.map(x=>({...x,restaurant_id:restaurant.id})));}})();},[restaurant?.id]);const avg=useMemo(()=>rows.length?rows.reduce((s,x)=>s+x.overall_rating,0)/rows.length:0,[rows]);const five=rows.filter(x=>x.overall_rating===5).length;return <div className="space-y-6"><PageHeader title="Feedback" description="See what guests think about the food and service."/><div className="grid gap-4 sm:grid-cols-3"><StatCard title="Average Rating" value={avg.toFixed(1)} icon={<Star size={20}/>} accent="orange"/><StatCard title="Responses" value={rows.length} icon={<MessageSquare size={20}/>} accent="blue"/><StatCard title="5-Star Reviews" value={five} icon={<SmilePlus size={20}/>} accent="green"/></div><div className="grid gap-4 lg:grid-cols-2">{rows.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-orange-50 font-bold text-brand-600">{(r.customer_name||'G')[0]}</div><div><p className="font-semibold text-slate-900">{r.customer_name||'Guest'}</p><p className="text-xs text-slate-400">{formatDate(r.created_at)}</p></div></div><div className="flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700"><Star size={13} className="fill-amber-400 text-amber-400"/>{r.overall_rating}</div></div><p className="mt-4 text-sm leading-6 text-slate-600">“{r.comment||'No written comment.'}”</p><div className="mt-4 flex gap-4 border-t border-slate-100 pt-3 text-xs text-slate-400"><span>Food {r.food_rating}/5</span><span>Service {r.service_rating}/5</span></div></article>)}</div></div>}
