import { useEffect, useState } from 'react';
import { Plus, Tag, Pencil, Trash2, TicketPercent } from 'lucide-react';
import { useAuth } from '@/lib/auth-context';
import { createOffer, deleteOffer, getOffers, updateOffer } from '@/lib/services';
import type { Offer } from '@/types';
import { ConfirmModal, Modal, Toast } from '@/components/ui';
import { PageHeader, Toggle, inputClass, labelClass } from '@/components/admin/PageBits';
import { demoOffers } from '@/data/demo';
import { formatCurrency } from '@/lib/utils';

const blank={name:'',coupon_code:'',discount_type:'percentage',discount_value:'10',minimum_order:'0',start_date:'',end_date:'',is_active:true};
export default function OffersPage(){const{restaurant}=useAuth();const[offers,setOffers]=useState<Offer[]>([]);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Offer|null>(null);const[form,setForm]=useState(blank);const[del,setDel]=useState<Offer|null>(null);const[toast,setToast]=useState<string|null>(null);
useEffect(()=>{if(!restaurant)return;(async()=>{try{const r=await getOffers(restaurant.id);setOffers(r);}catch{setOffers(demoOffers.map(x=>({...x,restaurant_id:restaurant.id})));}})();},[restaurant?.id]);
const add=()=>{setEditing(null);setForm(blank);setOpen(true)};const edit=(o:Offer)=>{setEditing(o);setForm({name:o.name,coupon_code:o.coupon_code,discount_type:o.discount_type,discount_value:String(o.discount_value),minimum_order:String(o.minimum_order),start_date:o.start_date||'',end_date:o.end_date||'',is_active:o.is_active});setOpen(true)};
const save=async()=>{if(!restaurant||!form.name||!form.coupon_code)return;const p={restaurant_id:restaurant.id,name:form.name,coupon_code:form.coupon_code.toUpperCase(),discount_type:form.discount_type,discount_value:Number(form.discount_value)||0,minimum_order:Number(form.minimum_order)||0,start_date:form.start_date||null,end_date:form.end_date||null,is_active:form.is_active};try{if(editing){const s=await updateOffer(editing.id,p);if(s)setOffers(v=>v.map(x=>x.id===editing.id?s:x));}else{const s=await createOffer(p);if(s)setOffers(v=>[s,...v]);}setOpen(false);setToast(editing?'Offer updated':'Offer created');}catch{setToast('Could not save offer')}};
const remove=async()=>{if(!del)return;try{await deleteOffer(del.id);setOffers(v=>v.filter(x=>x.id!==del.id));setToast('Offer deleted')}catch{setToast('Could not delete offer')}};
const toggle=async(o:Offer)=>{const n=!o.is_active;setOffers(v=>v.map(x=>x.id===o.id?{...x,is_active:n}:x));try{await updateOffer(o.id,{is_active:n})}catch{}};
return <div className="space-y-6"><PageHeader title="Offers & Coupons" description="Create discounts to increase order value and repeat visits." actions={<button onClick={add} className="inline-flex items-center gap-2 rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/> Create Offer</button>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{offers.map(o=><div key={o.id} className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="absolute -right-6 -top-6 h-20 w-20 rounded-full bg-orange-50"/><div className="relative"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-brand-600"><TicketPercent size={21}/></div><Toggle checked={o.is_active} onChange={()=>void toggle(o)}/></div><h3 className="mt-4 font-bold text-slate-900">{o.name}</h3><p className="mt-1 text-2xl font-black text-brand-600">{o.discount_type==='percentage'?`${o.discount_value}% OFF`:`${formatCurrency(Number(o.discount_value))} OFF`}</p><div className="mt-4 rounded-xl border border-dashed border-orange-200 bg-orange-50/60 px-4 py-3 text-center font-mono text-sm font-bold tracking-widest text-orange-800">{o.coupon_code}</div><p className="mt-3 text-xs text-slate-400">Minimum order {formatCurrency(Number(o.minimum_order))}</p><div className="mt-4 flex gap-2"><button onClick={()=>edit(o)} className="flex-1 rounded-xl border border-slate-200 py-2 text-xs font-semibold text-slate-600"><Pencil size={14} className="mr-1 inline"/>Edit</button><button onClick={()=>setDel(o)} className="rounded-xl border border-red-100 px-3 text-red-500"><Trash2 size={15}/></button></div></div></div>)}</div>
<Modal isOpen={open} onClose={()=>setOpen(false)} title={editing?'Edit Offer':'Create Offer'}><div className="space-y-4 p-6"><div><label className={labelClass}>Offer name</label><input className={inputClass} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Welcome Offer"/></div><div><label className={labelClass}>Coupon code</label><input className={inputClass} value={form.coupon_code} onChange={e=>setForm({...form,coupon_code:e.target.value.toUpperCase()})} placeholder="WELCOME10"/></div><div className="grid grid-cols-2 gap-3"><div><label className={labelClass}>Discount type</label><select className={inputClass} value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></div><div><label className={labelClass}>Discount value</label><input type="number" className={inputClass} value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})}/></div></div><div><label className={labelClass}>Minimum order</label><input type="number" className={inputClass} value={form.minimum_order} onChange={e=>setForm({...form,minimum_order:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className={labelClass}>Start date</label><input type="date" className={inputClass} value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></div><div><label className={labelClass}>End date</label><input type="date" className={inputClass} value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></div></div><Toggle checked={form.is_active} onChange={v=>setForm({...form,is_active:v})} label="Active offer"/><button onClick={()=>void save()} className="w-full rounded-xl bg-brand-500 py-3 text-sm font-bold text-white">Save Offer</button></div></Modal><ConfirmModal isOpen={!!del} onClose={()=>setDel(null)} onConfirm={()=>void remove()} title="Delete offer?" message="This coupon will no longer be available to customers." confirmLabel="Delete" danger/>{toast&&<Toast message={toast} type={toast.startsWith('Could')?'error':'success'} onClose={()=>setToast(null)}/>}</div>}
